import { index, jsonb, pgEnum, pgTable, text, timestamp, uuid } from 'drizzle-orm/pg-core';
import { organizations } from './organizations';
import { users } from './users';
import { idColumn } from './columns';

/**
 * "Retaining the bundle is what makes disputes resolvable — when a user says 'that number is
 * wrong', we can show exactly what produced it." A conversation is a thread of turns between one
 * user and the assistant, always org-scoped (I4) — no store scoping, matching the assistant's
 * framing as answering org-level business questions, not a store-specific tool (a question can
 * span stores, e.g. "which store has the worst food cost?").
 */
export const conversations = pgTable(
  'conversations',
  {
    id: idColumn(),
    organizationId: uuid('organization_id')
      .notNull()
      .references(() => organizations.id),
    userId: uuid('user_id')
      .notNull()
      .references(() => users.id),
    title: text('title'),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [index('conversations_org_user_created_at_idx').on(table.organizationId, table.userId, table.createdAt)]
);

export const messageRoleEnum = pgEnum('message_role', ['USER', 'ASSISTANT']);
export type MessageRole = (typeof messageRoleEnum.enumValues)[number];

/**
 * `organizationId` is a deliberate deviation from a first literal SQL sketch (which has only
 * `conversation_id`, no organization column) — confirmed with the user: every other tenant-scoped
 * child table in this codebase that could derive its tenant via a parent join instead carries its
 * own `organization_id` directly (`sales_transaction_lines`, `document_extractions`,
 * `recipe_components`), for real RLS + defense-in-depth (I4), matching `TenantScopedRepository`'s
 * own requirement that a table expose `organizationId` to be usable with it at all. Following
 * that first sketch literally here would mean either no RLS policy on `messages` at all, or a
 * policy backed by a subquery against `conversations` — a genuinely different, more fragile
 * mechanism than every other table's flat `organization_id = current_setting(...)` policy.
 * `denormalized` because the true owning relationship is still `conversationId →
 * conversations.organizationId`; this column is written once at insert time from the parent
 * conversation's own org, never updated independently.
 *
 * `groundingBundle`/`validationResult` are nullable — a `USER` message never has either (it wasn't
 * generated by the model); only an `ASSISTANT` message that actually ran a metric/retrieval call
 * carries a bundle. `content` is always the real, final text shown to the user — for an assistant
 * message whose first draft failed grounding validation ("violation → regenerate once → still
 * violating → discard the prose, render structured results only"), this is that post-fallback
 * text, never the discarded ungrounded draft; `validationResult` records what actually happened
 * during generation (including a fallback), independent of what the final `content` reads as.
 *
 * `modelVersion`/`promptVersion`/`catalogVersion` are named fields for exactly this
 * dispute-resolution purpose — a bundle alone doesn't explain *why* a later prompt change might
 * produce a different answer to the same question; these three pin down the full generation
 * context. All nullable for the same reason `groundingBundle` is: a `USER` message has none of
 * them, and no versioning scheme exists yet for any of the three (a later change will define what a
 * real value looks like) — this migration only establishes the columns, matching this project's
 * established pattern (see `documents.classificationConfidence`) of landing a schema ahead of the
 * code that populates it.
 */
export const messages = pgTable(
  'messages',
  {
    id: idColumn(),
    organizationId: uuid('organization_id')
      .notNull()
      .references(() => organizations.id),
    conversationId: uuid('conversation_id')
      .notNull()
      .references(() => conversations.id),
    role: messageRoleEnum('role').notNull(),
    content: text('content').notNull(),
    groundingBundle: jsonb('grounding_bundle'),
    modelVersion: text('model_version'),
    promptVersion: text('prompt_version'),
    catalogVersion: text('catalog_version'),
    validationResult: jsonb('validation_result'),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [index('messages_org_conversation_created_at_idx').on(table.organizationId, table.conversationId, table.createdAt)]
);
