import type { InvoiceGroundTruth } from "./types.js";

// Hand-authored ground truth. Written before any OCR runs — do not adjust
// these values after seeing extraction output.

export const fixtures: InvoiceGroundTruth[] = [
  {
    file: "nova-foods-8891",
    supplier: "Nova Foods Ltd",
    documentNumber: "INV-2024-8891",
    documentDate: "2024-03-14",
    currency: "USD",
    lines: [
      { sku: "FLR-T55-25", description: "Flour T55 25kg sack", quantity: "4", unit: "sack", unitPrice: "26.25", lineTotal: "105.00" },
      { sku: "SUG-CAS-25", description: "Caster Sugar 25kg", quantity: "2", unit: "bag", unitPrice: "31.40", lineTotal: "62.80" },
      { sku: "BUT-UNS-10", description: "Unsalted Butter 10kg block", quantity: "3", unit: "block", unitPrice: "58.90", lineTotal: "176.70" },
      { sku: "EGG-LRG-360", description: "Eggs, Large, tray of 30 (12 trays)", quantity: "12", unit: "tray", unitPrice: "8.15", lineTotal: "97.80" },
    ],
    discount: null,
    subtotal: "442.30",
    tax: "35.38",
    total: "477.68",
  },
  {
    file: "harborside-produce-0142",
    supplier: "Harborside Produce Co.",
    documentNumber: "HP-0142",
    documentDate: "2024-04-02",
    currency: "USD",
    lines: [
      { sku: null, description: "Roma Tomatoes", quantity: "18", unit: "kg", unitPrice: "2.85", lineTotal: "51.30" },
      { sku: null, description: "Yellow Onions", quantity: "25", unit: "kg", unitPrice: "1.10", lineTotal: "27.50" },
      { sku: null, description: "Romaine Lettuce", quantity: "6", unit: "case", unitPrice: "22.00", lineTotal: "132.00" },
      { sku: null, description: "Avocados, ripe", quantity: "4", unit: "case", unitPrice: "34.50", lineTotal: "138.00" },
      { sku: null, description: "Lemons", quantity: "10", unit: "kg", unitPrice: "3.20", lineTotal: "32.00" },
    ],
    discount: "10.00",
    subtotal: "380.80",
    tax: "0.00",
    total: "370.80",
    notes: "Loyalty discount applied as flat deduction. Produce is zero-rated for tax.",
  },
  {
    file: "coastal-meats-55210",
    supplier: "Coastal Meats & Poultry",
    documentNumber: "CM-55210",
    documentDate: "2024-04-18",
    currency: "USD",
    lines: [
      { sku: "CHK-BRST-BONE", description: "Chicken Breast, boneless skinless", quantity: "40", unit: "kg", unitPrice: "6.75", lineTotal: "270.00" },
      { sku: "BEEF-GRND-80", description: "Ground Beef 80/20", quantity: "30", unit: "kg", unitPrice: "8.20", lineTotal: "246.00" },
      { sku: "BACON-SLB", description: "Bacon, slab, smoked", quantity: "12", unit: "kg", unitPrice: "9.60", lineTotal: "115.20" },
    ],
    discount: null,
    subtotal: "631.20",
    tax: "50.50",
    total: "681.70",
  },
  {
    file: "nova-foods-8892",
    supplier: "Nova Foods Ltd",
    documentNumber: "INV-2024-8892",
    documentDate: "2024-03-15",
    currency: "USD",
    lines: [
      { sku: "FLR-T55-25", description: "Flour T55 25kg sack", quantity: "2", unit: "sack", unitPrice: "26.25", lineTotal: "52.50" },
      { sku: "YST-INST-1", description: "Instant Yeast 1kg vacuum pack", quantity: "5", unit: "pack", unitPrice: "14.75", lineTotal: "73.75" },
    ],
    discount: null,
    subtotal: "126.25",
    tax: "10.10",
    total: "136.35",
    notes: "Near-duplicate of nova-foods-8891: same supplier, consecutive invoice number, next-day date. Used to test duplicate-detection specificity (must NOT be flagged as a true duplicate).",
  },
  {
    file: "millbrook-dairy-3007",
    supplier: "Millbrook Dairy Cooperative",
    documentNumber: "MD-3007",
    documentDate: "2024-05-01",
    currency: "USD",
    lines: [
      { sku: "MLK-WHL-4L", description: "Whole Milk 4L jug", quantity: "20", unit: "jug", unitPrice: "5.40", lineTotal: "108.00" },
      { sku: "MLK-2PC-4L", description: "2% Milk 4L jug", quantity: "18", unit: "jug", unitPrice: "5.10", lineTotal: "91.80" },
      { sku: "MLK-SKM-4L", description: "Skim Milk 4L jug", quantity: "12", unit: "jug", unitPrice: "4.85", lineTotal: "58.20" },
      { sku: "CRM-HVY-1L", description: "Heavy Cream 1L", quantity: "15", unit: "carton", unitPrice: "4.85", lineTotal: "72.75" },
      { sku: "CRM-LGT-1L", description: "Light Cream 1L", quantity: "10", unit: "carton", unitPrice: "3.95", lineTotal: "39.50" },
      { sku: "CHS-MOZ-5KG", description: "Mozzarella, low-moisture, 5kg block", quantity: "6", unit: "block", unitPrice: "42.00", lineTotal: "252.00" },
      { sku: "CHS-PARM-2KG", description: "Parmesan, aged 18mo, 2kg wedge", quantity: "3", unit: "wedge", unitPrice: "68.50", lineTotal: "205.50" },
      { sku: "CHS-CHED-3KG", description: "Cheddar, sharp, 3kg block", quantity: "5", unit: "block", unitPrice: "31.20", lineTotal: "156.00" },
      { sku: "CHS-BRIE-1KG", description: "Brie, double-cream, 1kg wheel", quantity: "4", unit: "wheel", unitPrice: "24.75", lineTotal: "99.00" },
      { sku: "YOG-GRK-4KG", description: "Greek Yogurt, plain, 4kg tub", quantity: "8", unit: "tub", unitPrice: "19.20", lineTotal: "153.60" },
      { sku: "YOG-VAN-4KG", description: "Vanilla Yogurt, 4kg tub", quantity: "6", unit: "tub", unitPrice: "18.40", lineTotal: "110.40" },
      { sku: "BUTM-CULT-2L", description: "Cultured Buttermilk 2L", quantity: "10", unit: "carton", unitPrice: "6.10", lineTotal: "61.00" },
      { sku: "SCRM-FUL-500", description: "Sour Cream, full-fat, 500g tub", quantity: "14", unit: "tub", unitPrice: "3.15", lineTotal: "44.10" },
      { sku: "CTG-CHS-2KG", description: "Cottage Cheese 2kg tub", quantity: "7", unit: "tub", unitPrice: "12.60", lineTotal: "88.20" },
    ],
    discount: "25.00",
    subtotal: "1540.05",
    tax: "121.20",
    total: "1636.25",
    notes: "Multi-page: 14 line items deliberately laid out to force a page break in the rendered PDF.",
  },
  {
    file: "riverside-bakery-supply-9004",
    supplier: "Riverside Bakery Supply",
    documentNumber: "RBS-9004",
    documentDate: "2024-05-10",
    currency: "USD",
    lines: [
      { sku: "CHOC-DK-70-5KG", description: "Dark Chocolate 70% callets, 5kg", quantity: "3", unit: "bag", unitPrice: "48.00", lineTotal: "144.00" },
      { sku: "VAN-EXT-1L", description: "Vanilla Extract, pure, 1L", quantity: "2", unit: "bottle", unitPrice: "36.50", lineTotal: "73.00" },
      { sku: "ALM-FLR-10KG", description: "Almond Flour, blanched, 10kg", quantity: "1", unit: "sack", unitPrice: "89.00", lineTotal: "89.00" },
      { sku: "BAK-PWD-500G", description: "Baking Powder 500g tin", quantity: "6", unit: "tin", unitPrice: "3.40", lineTotal: "20.40" },
    ],
    discount: null,
    subtotal: "326.40",
    tax: "26.11",
    total: "352.51",
  },
  {
    file: "coastal-meats-55298",
    supplier: "Coastal Meats & Poultry",
    documentNumber: "CM-55298",
    documentDate: "2024-06-02",
    currency: "USD",
    lines: [
      { sku: "SALM-FIL-SK", description: "Salmon Fillet, skin-on, farmed", quantity: "15", unit: "kg", unitPrice: "14.80", lineTotal: "222.00" },
      { sku: "SHRP-21-25", description: "Shrimp 21/25, peeled & deveined", quantity: "10", unit: "kg", unitPrice: "17.25", lineTotal: "172.50" },
      { sku: "CREDIT-DMG", description: "Credit: damaged case, prior invoice CM-55210", quantity: "1", unit: "ea", unitPrice: "-18.00", lineTotal: "-18.00" },
    ],
    discount: null,
    subtotal: "376.50",
    tax: "28.68",
    total: "405.18",
    notes: "Credit line (negative quantity/total) for a prior damaged shipment.",
  },
];
